### PR TITLE
Take action on clearance request

### PR DESCRIPTION
**Pull request by humaneguy**
This PR implements the ability of a sectional administrator to approve and decline a student clearance status.🔥

### CODE REVIEW

**Comment by humaneguy** [comment]
- [ ] Leave the student with a message
- [ ] Request for changes.

**Review by anubra266 — COMMENTED** [review]
Why is it returningpure text

**Comment by humaneguy** [comment]
> Why is routes/web.php
> commit [47d40a4](https://github.com/humaneguy/clearme/commit/47d40a46248089ea0d902bb8d9f505f717f10038) returning pure text

That commit is a very old one. It gets update [here](https://github.com/humaneguy/clearme/pull/76/commits/ced363ecec64eb990c5a8cefbd7cc21256ca950e)

**Comment by humaneguy** [comment]
Nice work, dude!

**Pull request merged**
